### ISSUE TITLE
Work on your  README Live-Demo

### ISSUE THREAD

**Issue by MariamOsman11** [malembi/My-Portfolio#16]
On the readme file. your live demo link is not showing your portflio. Kindly link it.

**Comment by CaptainBawa** [comment]
![Capture](https://user-images.githubusercontent.com/82339317/224249219-3578beb5-692a-4b46-a534-c437056c383d.PNG)
-Nice work so far but I think you could have stretch your contact form to have at least 80% width of the page

**Comment by malembi** [comment]
completed.
