### ISSUE TITLE
Peer to peer code review on responsiveness of portfolio

### ISSUE THREAD

**Issue by Chandan-devs-tech** [malembi/My-Portfolio#17]
Hi @malembi,
- Great job you have done so far!
- Some  changes are required there in the responsiveness of the portfolio is:
# Required Changes ♻️ 
- Please remove the image from the "frame" class to the ul tag to make the portfolio look more responsive.
<img width="647" alt="samir" src="https://user-images.githubusercontent.com/65088027/224926106-6d0182f6-b297-48bf-ac6b-54911a563391.png">

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

**Comment by MariamOsman11** [comment]
@malembi kindly make sure your portflio is responsive to all screen sizes. Thank you

**Comment by malembi** [comment]
Thank you for reviewing the work.
