### ISSUE TITLE
Peer to peer code review on desktop version

### ISSUE THREAD

**Issue by Chandan-devs-tech** [malembi/My-Portfolio#8]
Hi @malembi 
# Change Required ♻️ 
- My coding partner and a collaborator on this desktop version portfolio project are supposed to make at least one commit on the code and add the keyframes for animation on the logo.

<img src="https://media0.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

**Comment by malembi** [comment]
The collaborator completed the required task perfectly.
